version: '3.8'
services:
  dev-postgres:
    image: postgres:14.4-alpine
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: reat-api-by-nest
      POSTGRES_PASSWORD: reat-api-by-nest
      POSTGRES_DB: reat-api-by-nest
    restart: always
    networks:
      - lesson
networks:
  lesson:
